### ISSUE TITLE
peer to peer review

### ISSUE THREAD

**Issue by xtrahuman** [blessedjasonmwanza/todo-list#8]
# Review on test functions
I think it will be nice to group descriptions of checked and clear all separately so that the errors descriptions can easily be traced by descriptions if any

**Comment by blessedjasonmwanza** [comment]
Hello @xtrahuman ,

Thank you a lot for this review. We will surely apply the suggested changes where applicable.

> Cheers and, HappyCoding 👨🏽‍💻
