### ISSUE TITLE
Suggested Changes ♻️ 

### ISSUE THREAD

**Issue by brytebee** [blessedjasonmwanza/todo-list#9]
Hi @blessedjasonmwanza & @ShoiraTa 👋👋

You have done an amazing job coming so far with the application.
### Highlights 💡💡
- Your UI is so smooth and meets the required design. Kudos ✔️✔️
- Your code is modular ✔️💯 

## Suggested Changes ♻️ 
However, they are a few changes you could make to your project.
- **OPTIONAL:** Consider adding a screenshot of the app design to the README.md, as this gives a visual representation of the app.

**_Happy hacking_** 😏😏

**Comment by blessedjasonmwanza** [comment]
Hello @brytebee ,

Thank you for such an uplifting review.

I am on to making the suggested changes right away.

> HappyCoding 👨🏽‍💻
